<?php

/**
* 对于原来的商品分类库累觉不爱。
* 邪恶的大鲵语录 “让我们伸出触手！”
*/
class CategoryAgency
{
	
	function __construct()
	{
		# code...
	}

	public static function getCategoryTreeWithPartyId($party_id=null,$top_cat_id_list=array()){
		global $db;

		$party_ids=CategoryAgency::getPartyIdWithRootPartyId($party_id);

		$party_ids_sql=implode(",",$party_ids);

		$sql="SELECT
			cat_id,cat_name,parent_id
		FROM
			ecshop.ecs_category
		WHERE
			is_delete = 0
		AND party_id IN ({$party_ids_sql})";
		$lines=$db->getAll($sql);
		$c_set=$p_set=array();
		foreach ($lines as $line) {
			$c_set[$line['cat_id']]=$line['cat_id'];
			$p_set[$line['cat_id']]=$line['parent_id'];
		}
		$top_cat_list=array_keys(array_diff($p_set,$c_set));
		
		$trees=array();

		foreach($top_cat_list as $root_id){
			if(!empty($top_cat_id_list) && !in_array($root_id,$top_cat_id_list)){
				continue;
			}

			$sql="SELECT
				cat_id,cat_name,party_id
			FROM
				ecshop.ecs_category
			WHERE
				cat_id={$root_id}
			LIMIT 1
			";
			$tree=$db->getRow($sql);
			$tree['children']=CategoryAgency::getAllSubCategoriesAsTree($root_id);
			$trees[]=$tree;
		}
		
		return $trees;
	}

	/**
	 * Generate HTML codes for Data Structure generated by getCategoryTreeWithPartyId method 
	 * @param  String $node     One node of one stem of one tree generated by above
	 * @param  String $mukuteki Value of "list" or "edit"
	 * @return String HTML codes used in category_tree.htm
	 */
	public static function parseSinriCategoryTreeNodeToHTML($node,$mukuteki){
		if($mukuteki=='list'){
			$act="list";
			$target='content';
		}elseif($mukuteki=='edit'){
			$act='edit';
			$target='edit_content';
		}
		$html="<li>";
		if(empty($node['children'])){
			$html.="<a href='goods_index.php?act={$act}&cat_id=".$node['cat_id']."' target='{$target}'>".
					"<span class='file'>".$node['cat_name']."</span>".
					"</a>";
		}else{
			$html.="<span class='folder' id='".$node['cat_id']."'>".$node['cat_name']."</span>";
			$html.="<ul>";
			foreach ($node['children'] as $child) {
				$html.=CategoryAgency::parseSinriCategoryTreeNodeToHTML($child,$mukuteki);
			}
			$html.="</ul>";
		}
		$html.="</li>";
		return $html;
	}

	public static function getAllSubCategoriesAsTree($root_id=0){//echo "[$root_id]";
		global $db;

		$tree=array();

		$sql="SELECT
			cat_id,cat_name,party_id
		FROM
			ecshop.ecs_category
		WHERE
			is_delete = 0
		AND parent_id={$root_id}
		";
		$lines=$db->getAll($sql);

		foreach ($lines as $line) {
			$tree[$line['cat_id']]=$line;
			$tree[$line['cat_id']]['children']=CategoryAgency::getAllSubCategoriesAsTree($line['cat_id']);
		}

		return $tree;
	}

	/**
	 * @deprecated
	 * @param  [type] &$categoryBasicInfo [description]
	 * @return [type]                     [description]
	 */
	public static function getCategoryRootPath(&$categoryBasicInfo){
		if($categoryBasicInfo['parent_id']!=0){
			$categoryBasicInfo['parent_cat_info']=CategoryAgency::getCategoryBasicInfo($categoryBasicInfo['parent_id']);
			if(!empty($categoryBasicInfo['parent_cat_info']['parent_id'])){
				CategoryAgency::getCategoryRootPath($categoryBasicInfo['parent_cat_info']);
			}
		}else{
			$categoryBasicInfo['parent_cat_info']=null;
		}
	}

	public static function getCategoryBasicInfo($cat_id){
		global $db;

		$sql="SELECT cat_id,cat_name,parent_id 
		FROM ecshop.ecs_category
		WHERE
			is_delete = 0
		AND cat_id={$cat_id}
		LIMIT 1
		";
		return $db->getRow($sql);
	}

	public static function getPartyIdWithRootPartyId($party_id=null){
		global $db;

		if($party_id==null){
			$sql="SELECT
				PARTY_ID
			FROM
				romeo.party
			WHERE
				STATUS = 'ok'
			AND (
				system_mode = '2'
				OR system_mode = '3'
			)
			-- AND PARTY_ID = '{$party_id}'
			";
			$list=$db->getCol($sql);
		}else{
			$list=array($party_id);
	        
	        $i=0;
	        while($i<count($list)){
				$sql="SELECT
					PARTY_ID
				FROM
					romeo.party
				WHERE
					STATUS = 'ok'
				AND (
					system_mode = '2'
					OR system_mode = '3'
				)
				AND PARENT_PARTY_ID = '{$list[$i]}'
				";
				$tlist=$db->getCol($sql);
				foreach ($tlist as $key => $value) {
					$list[$value]=$value;
				}
				$i++;
	        }
		}
        return $list;        
	}

}

/**
* 
*/
class SinriCategoryTree
{
	private $index_by_parent_id=array();
	private $index_by_cat_id=array();
	public $trees;


	function __construct()
	{
		$this->trees=array();
	}

	public function testTree(){
		global $db;

		$sql="SELECT cat_id,cat_name,party_id,parent_id FROM ecshop.ecs_category WHERE is_delete = 0";
		$list=$db->getAll($sql);
		foreach($list as $line){
			// The CAT index
			$this->index_by_cat_id[$line['cat_id']]=$line;
			// The parent index
			if(!isset($this->index_by_parent_id[$line['parent_id']])){
				$this->index_by_parent_id[$line['parent_id']]=array();
			}
			$this->index_by_parent_id[$line['parent_id']][$line['cat_id']];

		}

		$root_id=0;
		$this->trees=$this->goEda($root_id);
	}

	public function goEda($root_id){
		$subArray=array();
		foreach($this->index_by_parent_id[$root_id] as $cat_id){
			$t=$this->index_by_cat_id($cat_id);
			$t['children']=$this->goEda($cat_id);
			$subArray[$cat_id]=$t;
		}
		return $subArray;
	}
}